### ISSUE TITLE
Rendering of points not working

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#179] opened 2020-10-06 20:08 UTC
To reproduce, use this document:

```html
<mapml lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/mapml" />
    <title>A point in Map Markup Language</title>
    <meta name="projection" content="CBMTILE"/>
    <!-- I *thought* that you could specify a value=n in the zoom meta content,
         and that would be used for the native zoom of features if they don't have
         a zoom attribute?  Can't make this work, you need the feature.zoom property  -->
    <meta name="zoom" content="min=0,max=22,value=3" />
    <link rel="license" href="foo" title="Foo © Natural Resources Canada" />
  </head>
  <body>
    <!-- zoom is a property of static features, represents "native" zoom concept -->
    <feature id="palais" zoom="3">
      <properties>
        <name>Palais des congrès de Montréal</name>
      </properties>
      <!-- cs is a property of anything that has parseable coordinates as content -->
      <geometry cs="gcrs">
        <point>
          <coordinates>-73.5602045 45.5038505</coordinates>
        </point>
      </geometry>
    </feature>
  </body>
</mapml>
```

[Lines 270-276](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/21af883778dedf1b32bcd063b04ba9911d1ce08f/src/mapml/layers/FeatureLayer.js#L270-L276) of FeatureLayer.js contain the relevant code.  A long standing issue with the code is that the points are rendered as Leaflet markers, which is great, but the intent is to be able to style points using native CSS/SVG techniques, so we have to re-think what the renderer should do to simulate that.

**Comment by prushforth** [comment] 2020-10-06 21:32
So the point does render, but maybe there are some semantics that I'm misunderstanding, or forgetting, about `<meta name=zoom content="min=0,max=22,value=3"/>` (for example).  See comments in palais.mapml.

**Comment by ahmadayubi** [comment] 2021-01-07 18:12
I think this issue can be closed as I couldn't reproduce it.

**Closed** 2021-01-07 20:21 UTC
