### ISSUE TITLE
Vector tile rendering bug (?)

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Web-Map-Custom-Element#504] opened 2021-08-05 18:30 UTC
[This page](https://maps4html.org/experiments/vector-tiles/mapml/mapml-viewer/tile-rendering-bug/) shows that the axis order of rendered OSMTILE / pcrs coordinates is reversed (or something, maybe some other problem). The question is: is this a rendering bug, or a source problem.  The source is [here](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad/0/0/0.mapml), for example (WebMercatorQuad is equivalent to OSMTILE, I believe, so the axis order should be the same E,N).

![image](https://user-images.githubusercontent.com/2437285/128402205-b7c060bb-9b03-417d-9a6c-3e2522d60484.png)

(Canada is drawn in blue vector).

**Comment by prushforth** [comment] 2021-08-07 13:04
@jerstlouis I believe the axis order in[ this service ](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad/0/0/0.mapml)is reversed (it is [northing easting] but should be [easting northing]).  There are other things, but that is the most important that I thought you might want to know about.  Also, the document could include a `<meta name="projection" content="OSMTILE" /> <meta name="cs" content="PCRS"/>` element pair to be strictly correct, I believe.  Not sure if you care enough to fix that stuff at this point, but you know we're always willing to entertain testbed proposals for that kind of thing :-)

**Comment by jerstlouis** [comment] 2021-08-07 22:18
@prushforth I sure care and will take a look and fix it ASAP. Thanks for point this out! Please feel free to point out any other problems on our service.

**Comment by prushforth** [comment] 2021-08-07 22:34
Ok, I'll make a short list of suggestions. Some issues may be only because the spec has moved since the service was created. I'll try to identify differentiate any case like that. Thanks!

**Comment by jerstlouis** [comment] 2021-10-30 19:52
@prushforth The axis order issue should be fixed now. Sorry for the delays in correcting this. Thanks again for spotting the issue! Please let me know if there are any additional problems to resolve.

**Comment by prushforth** [comment] 2021-10-30 20:00
Hi @jerstlouis thank you very much for fixing it! I'll check it out soon.

**Comment by prushforth** [comment] 2021-11-01 19:27
@jerstlouis I am working on documenting some of the changes that we've made to MapML since your services were authored, in case you may be interested, but one issue I am seeing in the [WebMercatorQuad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad/0/0/0.mapml) service is the presence of this number: 0.0000000007081 a bunch of times, yielding "zinger" artifacts I _believe_.

**Comment by jerstlouis** [comment] 2021-11-01 19:37
@prushforth Thanks for spotting this. I will open an issue to investigate this.

Would you be able to describe which artifacts you think are caused by this? A screenshot would be super useful. If you have a link to an online client where we can experience that, that would be even better.

Also out of curiosity, are you already using those `<span class='noline'>` to avoid drawing stroked for artificial edges introduced by tiles in your client?

Thank you!

**Comment by prushforth** [comment] 2021-11-02 01:28
@jerstlouis I'm not confident I can correlate those numbers with any visual artifacts.  I have to use an older version of our custom element to view the service now, so I also can't swear that some of the visual artifacts in this screen shot aren't caused by my stylesheet or something else in the rendering pipeline.  This screen cap is at zoom=4:

![image](https://user-images.githubusercontent.com/2437285/139772002-8ec8f357-eae7-4c13-b87c-5ec21391830d.png)

> Also out of curiosity, are you already using those <span class='noline'> to avoid drawing stroked for artificial edges introduced by tiles in your client?

Yes, we are using the span (now map-span) to style them.

**Comment by jerstlouis** [comment] 2021-11-02 01:44
@prushforth The 0.0000000007081 are gone, I put in a work around.

Please let me know if that solves your issue, although I have some doubts that this was the cause.

Somehow `tan((Pi / 2 - latitude) / 2)` when `latitude` is 0 was evaluating to an extremely tiny bit less than exactly 1.0, perhaps from optimizations, and this was the results.

I also reduced the number of decimals for those projected coordinates, which would also avoided those far away digits.

**Comment by jerstlouis** [comment] 2021-11-02 01:58
@prushforth I checked with the QGIS "Vector / Check Validity" tool, and it currently reports invalid polygons and errors, which are likely self-intersecting polygons.

I am guessing these are the ones your renderer is struggling with. Ideally, our server should not return self-intersecting geometry. That will be a bit more difficult to fix though, but I filed an issue to tackle this as soon as we have free cycles.

**Comment by prushforth** [comment] 2021-11-02 02:01
Hi @jerstlouis I very much appreciate your even looking at this at this stage. I will still send you a list of vocabulary refactoring we did, maybe it will come into play if we ever are able to collaborate in a testbed or something like that. Cheers!

**Comment by prushforth** [comment] 2021-11-02 18:31
@jerstlouis The axis order issue is definitely resolved. Thanks! 

I think all those small numbers were causing horizontal lines in zoom=0 (at least).  They are definitely gone now. 

The artifacts with polygons and (a few) un-spanned tile segments remain, as far as I can tell. 

I made an offline copy of your level 0-2 tiles to support [this example page](https://maps4html.org/experiments/vector-tiles/mapml/mapml-viewer/).  I had to make it offline so that I could refactor the element names per this year's evolution of mapml.  I include the [XSLT stylesheet I used to do that refactoring](https://github.com/Maps4HTML/experiments/blob/main/vector-tiles/mapml/tiles/refactor.xsl), in case you ever have the opportunity to upgrade, the mappings should all be there.  The comments in there also may be of interest.

Cheers

**Comment by jerstlouis** [comment] 2021-11-02 18:42
Thanks @prushforth .The example stripped out all of the properties, would those change in any way?

**Comment by prushforth** [comment] 2021-11-02 18:45
The properties are unchanged, we just haven't thought about how to present
them, and because they take up space, I just suppressed them for now.

**Comment by jerstlouis** [comment] 2021-11-02 19:05
@prushforth Most of these changes should be applied now:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad/0/0/0.mapml

except I did not remove the base and extent stuff yet. Let me know if that's an issue and you just want to me to take it out.

Also I noticed your the tiles you had set up did not use the latest version with reduced number of decimals.

About un-spanned tile segments, I believe I have seen this before and it is something we need to look into.

In terms of the polygon fill issues, I don't see those. I see some odd strokes rendering though, e.g. in the US around the Gulf of Mexico. I'm not sure if this is is a result of self-intersecting polygons.

**Comment by prushforth** [comment] 2021-11-03 15:38
@jerstlouis 

> except I did not remove the base and extent stuff yet. Let me know if that's an issue and you just want to me to take it out.

The extent is probably harmless, but note it is tagged units="WGS84" which refers to a different tiling scheme. In MapML the correct scheme would be "OSMTILE" in this context.

The base should be ok, since it is for your service.  

> In terms of the polygon fill issues, I don't see those. I see some odd strokes rendering though, e.g. in the US around the Gulf of Mexico. I'm not sure if this is is a result of self-intersecting polygons.

I think there is at least one rendering [bug](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/559), so we'll investigate. 

> About un-spanned tile segments, I believe I have seen this before and it is something we need to look into.

Cool, thank you for your contribution!

**Comment by jerstlouis** [comment] 2021-11-03 15:46
> note it is tagged units="WGS84" which refers to a different tiling scheme. In MapML the correct scheme would be "OSMTILE" in this context.

In that case, it refers to the coordinates expected for the location inputs (and for `&clipbox=`) within the map-extent which are still in WGS84. I'm not sure if that could be possible to have coordinates in EPSG:3857 but extents / inputs in CRS84. We still need to implement support for `bbox-crs` (and `clipbox-crs`?) to qualify the specified bbox coordinates system as not CRS84.

**Comment by prushforth** [comment] 2021-11-03 15:52
For the location inputs, they are tagged units="gcrs", which stands for geographic coordinate reference system, which in the case of OSMTILE is indeed WGS 84 lon,lat / CRS84

**Comment by jerstlouis** [comment] 2021-11-03 18:14
@prushforth Fixed the `map-extent` units to say "OSMTILE".

Note that this is very confusing, because within that tag are map-inputs, which is the only thing that describes the extent, and what you might think the units apply to.

If the intent is to describe the CRS and tiling scheme of the feature geometries outside of this tag, it is really not obvious.

I dislike XML elements vs. attributes which I think contribute to the confusion -- no such mess in JSON.

My suggestion would be to use something like:

```
   <map-tilematrixset>http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad</map-tilematrixset>
   <map-crs>http://www.opengis.net/def/crs/OGC/1.3/CRS84</map-crs>
```

where it would be clearer that this applies to the document as a whole.

**Comment by prushforth** [comment] 2021-11-03 19:45
> Note that this is very confusing, because within that tag are map-inputs, which is the only thing that describes the extent, and what you might think the units apply to.

I appreciate the confusion.  I think we are tending towards the `extent@units` only identifying the TCRS of that extent, as we plan to allow > 1 `extent` per document.  If I had to start over, I would not likely have used "units" there, probably "projection" as we did with `map@projection`.  When this gets to a working group, I hope that will be the opportunity to refine some of the naming.  The `map-input@units` I think is a bit more meaningful as the value tells you directly how to parse (and transform) what you get back as a coordinate part.  For lack of a better link, [here](https://maps4html.org/MapML/spec/#coordinate-reference-system-type-codes-and-descriptions) are the `map-input@units` keywords.

> If the intent is to describe the CRS and tiling scheme of the feature geometries outside of this tag, it is really not obvious.

No that's not the intent, the intent is to identify in a single token the tile matrix set and the associated CRS interior coordinate systems of **that** `extent`, sort of like an EPSG code, but with the tile structure also determined.  But, we've had this conversation in depth before!

> where it would be clearer that this applies to the document as a whole.

The `<map-meta name="" content=""></map-meta>` tag is how we provide that info now, including the names: `extent`, `cs`, `projection`, and `zoom`

**Closed** 2021-11-03 19:45 UTC
Labels: bug

**Comment by prushforth** [comment] 2021-11-03 20:07
@jerstlouis I guess the WebMercatorQuad and WorldWGS84Quad services are independent instances? If I look at the WorldWGS84Quad tiles the element names are the non-map- ones.

**Comment by jerstlouis** [comment] 2021-11-03 20:58
@prushforth We currently have one _GNOSIS Map Server_ demo [instance](http://maps.ecere.com/ogcapi) serving all of the data.

Do you mean World**CRS84**Quad ?

The [NaturalEarth Countries](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries) are available as vector tiles at:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles

in different TileMatrixSets, including:

- [GNOSISGlobalGrid ](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/GNOSISGlobalGrid)
- [WorldCRS84Quad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldCRS84Quad)
- [WebMercatorQuad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad)
- [WorldMercatorWGS84Quad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldMercatorWGS84Quad)

maps are also available if you add `/map/` before `/tiles` to the same paths:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map/tiles

also in different TileMatrixSets, e.g.:

- [GNOSISGlobalGrid ](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map/tiles/GNOSISGlobalGrid)
- [WorldCRS84Quad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map/tiles/WorldCRS84Quad)
- [WebMercatorQuad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map/tiles/WebMercatorQuad)
- [WorldMercatorWGS84Quad](https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/map/tiles/WorldMercatorWGS84Quad)

**Comment by prushforth** [comment] 2021-11-05 00:44
Hi @jerstlouis 

> We currently have one GNOSIS Map Server demo instance serving all of the data.

I was confused by [this service](https://maps.ecere.com/geoapi/collections/NaturalEarth/cultural/ne_10m_admin_0_countries/tiles/WorldCRS84Quad/0/0/0.mapml), I believe

> Do you mean WorldCRS84Quad ?

Yes, sorry. I believe that should correspond with our ["WGS84" projection](https://maps4html.org/MapML/spec/#tcrs-WGS84), which has two tiles at level 0.

In this tile: https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldCRS84Quad/0/0/0.mapml 

I see a few errors

- axis order appears to be lat,lon; if it conforms to CRS84, it should be lon,lat
- `      <map-meta name='cs' content='pcrs'></map-meta>` should work, it's not an error, but I would use 'gcrs' to be certain (the lon,lat axis values of feature geometries in gcrs coordinates are identical in their values in the pcrs, but I suppose the pcrs "canvas" coordinate space is potentially infinite)
- should include `<map-meta name='projection' content='WGS84'></map-meta>` to clearly identify the [TCRS](https://maps4html.org/MapML/spec/#tcrs-WGS84), hence what is meant by gcrs, pcrs, tcrs etc.

**Comment by jerstlouis** [comment] 2021-11-05 19:40
Hi @prushforth,

> I was confused by this service, I believe

Oh, yes sorry, the `/geoapi` service is the separate old service back from 2019 / Testbed-15. It was mostly kept running for your convenience. Since you are now making use of the more recent service at `/ogcapi` we will likely take it offline soon to avoid such confusion.

> Yes, sorry. I believe that should correspond with our "WGS84" projection, which has two tiles at level 0.

That's correct. It skips the first scale from the [WMTS](https://portal.ogc.org/files/?artifact_id=35326) Annex E.3 Well-Known Scale Set _GoogleCRS84Quad_ which has a single tile for the whole world, but which some are struggling with because it specifies an odd `topLeftCorner` (now `pointOfOrigin`) at _latitude = 180_ and has empty bars at the top and bottom (we also support that one as a separate [TileMatrixSet](https://maps.ecere.com/ogcapi/tileMatrixSets/GoogleCRS84Quad)).

> axis order appears to be lat,lon; if it conforms to CRS84, it should be lon,lat

That is now fixed. The geographic TileMatrixSets on our service all assumed EPSG:4326, even those that are specified to use CRS84 in the registry. Now only [_GNOSISGlobalGrid_](https://maps.ecere.com/ogcapi/tileMatrixSets/GNOSISGlobalGrid) and [_CDBGlobalGrid_](https://maps.ecere.com/ogcapi/tileMatrixSets/CDBGlobalGrid) use EPSG:4326 (as specified in the new 2DTMS&TSMD revision).

As previously [discussed](https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/36) at length, it would still be possible for _TileSets_ to specify EPSG:4326 or another [compatible](https://docs.opengeospatial.org/DRAFTS/17-083r3.html#TileMatrixSetCRSCompatibility) CRS which is a specific realization of it (or adds a third or fourth dimension, e.g. [CRS84h](https://www.opengis.net/def/crs/OGC/0/CRS84h) or [EPSG:4979](https://epsg.io/4979), or time), while conforming to the _WorldCRS84Quad_ TileMatrixSet. For this reason, a client should ideally look at the `crs` property of https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldCRS84Quad?f=json and either reject the TileSet as not supported (perhaps selecting another one instead if available in the same TileMatrixSet, but in the desired CRS), or adjust as necessary. I recently suggested [making this `crs` property mandatory](https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/55) in the [TileSet metadata](https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/standard/figures/TileSet.png) to facilitate this and avoid any confusion. This only impacts vector formats like _MapML_ which don't explicitly state the CRS / axis order, unlike GeoJSON which stipulates CRS84.

>  I would use 'gcrs' to be certain (the lon,lat axis values of feature geometries in gcrs coordinates are identical in their values in the pcrs

Made the change.

> should include <map-meta name='projection' content='WGS84'></map-meta> to clearly identify the TCRS

Done.

Thank you for reporting these issues!

**Comment by prushforth** [comment] 2021-11-08 19:20
@jerstlouis 

> some are struggling with because it specifies an odd topLeftCorner (now pointOfOrigin) at latitude = 180

Which doesn't exist unless you think about these lat/lon as pcrs (infinite canvas) coordinates, which is reasonable, I think.

> This only impacts vector formats like MapML which don't explicitly state the CRS / axis order, unlike GeoJSON which stipulates CRS84.

MapML does explicitly state CRS and axis order, under "GCRS" column of [this table](https://maps4html.org/MapML/spec/#tiled-coordinate-reference-systems-0), as explained further by the table footnote:

> \* All coordinate reference systems' coordinate pairs, where not explicitly marked up or identified by axis (for example, in the coordinates element) are defined by this specification to be in "horizontal axis followed by vertical axis" order. Where axes order is defined differently by external definition, this specification MUST be taken to be correct for MapML documents.

> Thank you for reporting these issues!

I've updated the demonstration page to use your service endpoints now.  Thank you for following this effort!

**Comment by jerstlouis** [comment] 2021-11-08 19:38
@prushforth 

> MapML does explicitly state CRS and axis order, under "GCRS" column of this table, as explained further by the table footnote:

Based on that, what would that mean for _OGC API - Features_ with CRS support?

e.g.
https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items?f=mapml&crs=EPSG:4326

This is currently returned in _lat,_ lon order, as EPSG:4326 specifies.
That is also the case for GeoJSON, as that consitutes a pre-arrangement that EPSG:4326 is expected:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items?f=json&crs=EPSG:4326

And for TileMatrixSets / TileSets using EPSG:4326 as well:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/GNOSISGlobalGrid/0/0/0?f=mapml

That is also currently returned in _lat, lon_ order.

In the case of GeoJSON, that on the other hand is currently returned in _lon, lat_ order, as the CRS is not explicitly stated in the request:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/GNOSISGlobalGrid/0/0/0?f=json

If a `crs=EPSG:4326` parameter is included in the _Tile_ request however, the response will be in _lat, lon_ order as per the CRS:

https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/GNOSISGlobalGrid/0/0/0?f=json&crs=EPSG:4326

It would be good to clarify all of those cases for MapML.

Thank you!

**Comment by prushforth** [comment] 2021-11-09 14:54
> Based on that, what would that mean for _OGC API - Features_ with CRS support?
> 
> e.g.
> 
> 1. https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/items?f=mapml&crs=EPSG:4326
> 
> This is currently returned in _lat, lon_ order, as EPSG:4326 specifies. That is also the case for GeoJSON, as that consitutes a pre-arrangement that EPSG:4326 is expected:

GeoJSON does give wiggle room, unfortunately, but MapML, like KML does not.  What we want to avoid is anyone looking at a MapML document and wondering what the coordinate order of that document is, without being an expert even.  It will **always** be horizontal followed by vertical.  The URL parameter may not be around when the document is saved and emailed, and even if it was, we want to preserve the value of the simplicity of being able to look at the file and know what the coordinate order is.

> It would be good to clarify all of those cases for MapML.

Ignore the parameter, or don't serve/support MapML, or throw an exception, I think.  We don't want to invite axis order confusion.

**Comment by jerstlouis** [comment] 2021-11-09 16:07
@prushforth I think this would currently be handled by Case 4 of the [OGC axis order policy directive](https://portal.ogc.org/files/?artifact_id=76024):

> Case 4: The Encoding specification (document) explicitly overrides the Axis Order as specified in the CRS metadata:

In that case, no matter what the TileMatrixSet or TileSet CRS says about axis order, the payload will always be encoded according to the axis order specified by the MapML specification.

However the recommendation says for Case 4:

> The OGC does not recommend implementing this use case.

The recommended approaches are 1, 2 or 3, e.g.

> Case 1: Axis Order is defined by the CRS specified in the interface, protocol, or payload:

I am not sure if the MapML specification requiring the CRS to be specified (with values limited to CRS following Easting, Northing or Latitude, Longitude order) would be sufficient to follow the directive recommendation. The current approach for with `<meta name="projection"` and `<meta name="cs" ` is probably not however, as it states:

> The CRS SHALL be defined either by value, by reference, via a URL (current OGC policy), or by use of a URN as specified in OGC OWS Common [05-023r9].

so it would need to explicitly include something like `http://opengis.net/def/crs/EPSG/0/3857`.

I am also trying to get clarifications as to how approaches 2 and 3 can be implemented by referencing axes names, as there has been issues with this in the past (e.g. with CIS).

> Case 2: Payload encoding explicitly overrides the Axis Order as specified in the CRS metadata:
> Case 3: Payload includes metadata for a derived CRS or a local CS transformation setting Axis Order:

In the meantime, we will update our server to always return longitude, latitude or Easting, Northing for MapML payloads.

However I would suggest to reword _"horizontal axis followed by vertical axis"_ because in the context of a geographic CRS potentially having a 3rd dimension, the "vertical" axis [refers to height above the ellipsoid](https://docs.opengeospatial.org/is/18-010r7/18-010r7.html#47). Would MapML ever support geodesic CRSes (e.g. geocentric X, Y, Z like EPSG:4978)? Explicitly differentiating between projected CRSes (referring to axes as Easting, Northing) and geographic CRSes (referring to axes as longitude and latitude) would make things a lot clearer.

Thank you!

**Comment by prushforth** [comment] 2021-11-09 17:07
> Case 4: The Encoding specification (document) explicitly overrides the Axis Order as specified in the CRS metadata:

When we first proposed TMS 1.0 we proposed that TMS be _treated_ as CRS, with their metadata registered, so that

> Case 1: Axis Order is defined by the CRS specified in the interface, protocol, or payload
>The CRS SHALL be defined either by value, by reference, via a URL (current OGC policy), or by use of a URN as specified in OGC OWS Common [05-023r9].

would be satisfied by specifying "OSMTILE" which is an identifier token (by reference) that we had to create to avoid relying on URNs and URLs (having no precedent in HTML, would not fly with browsers)

We have proposed that some research be done in Testbed 18 to evaluate if it's currently possible (or if not, what extension is required) to encode complete TCRS definitions in proj JSON / CRS WKT, so that these CRS definitions can indeed be registered, even potentially within the EPSG dataset.

> However I would suggest to reword "horizontal axis followed by vertical axis" because in the context of a geographic CRS potentially having a 3rd dimension, the "vertical" axis refers to height above the ellipsoid. Would MapML ever support geodesic CRSes (e.g. geocentric X, Y, Z like EPSG:4978)? Explicitly differentiating between projected CRSes (referring to axes as Easting, Northing) and geographic CRSes (referring to axes as longitude and latitude) would make things a lot clearer -- as a 3D GIS person to me Easting is NOT horizontal and Northing is NOT vertical :).

Indeed it will require more text to do that, and "horizontal" etc. are relative to the client rendering viewport / 2D coordinate system, but point taken.  The goal is clarity, but nobody reads anything anyone else writes nowadays, so more text isn't always clearer!

I hope that we'll investigate creating 3D TCRS in Testbed 18 or a future testbed.  It could be important, for example, to specify a building floor plan at the the correct elevation and so on.  I don't know too much about 3D processing, actually, so interested to see what the experts have to say.

**Comment by jerstlouis** [comment] 2021-11-09 18:01
@prushforth 

> When we first proposed TMS 1.0 we proposed that TMS be treated as CRS, with their metadata registered

My opinion on that is that while TileMatrixSets can also be specified and registered in a similar way to CRSes, a tiling scheme is a different beast than a Coordinate Reference System. I think you handle that by calling this a `TCRS`. In a sense, perhaps it is somewhat like a different kind of CRSes like geodetic vs. geographic vs. projected. But TileMatrixSets have matrix, row, column identifiers, and then you still need additional coordinates within each tile's space. The OGC definition servers already has a [separate registry](http://www.opengis.net/def/tms) for TileMatrixSets, so I feel like at this point we should not conflate Coordinate Reference Systems with TileMatrixSets.

> We have proposed that some research be done in Testbed 18 to evaluate if it's currently possible (or if not, what extension is required) to encode complete TCRS definitions in proj JSON / CRS WKT

The TileMatrixSet specification specifies a _https://docs.opengeospatial.org/DRAFTS/17-083r3.html#tms-json-encoding_ for defining TileMatrixSets. It also supports either referencing by URL or embedding a CRS definition (potentially as PROJSON or a new eventual WKT2CRS JSON definition by OGC). Those definitions would also be available from the OGC TileMatrixSet registry.

> so that these CRS definitions can indeed be registered, even potentially within the EPSG dataset.

TileMatrixSets can be registered with the OGC TileMatrixSets registry. As well, we recently clarified that they could also be registered in other authoritative registries (e.g. set up by NRCan or IOGP). But neither version 1 or the upcoming revision 2, nor any other specification that I know of (except MapML) reference TileMatrixSets as "CRS". Although the DGGS specification (which in the case of _Part 4: axis aligned DGGS_ I think shares a lot with TileMatrixSets) does have this similar concept that the DGGS is a reference system.

So my feeling is that this is more of a policy/standards program issue than a technical capability to investigate. A TileMatrixSet and its CRS (by reference, or embedded) can already be fully described in a JSON document. But OGC specifications so far calls these TileMatrixSets, not (T)CRS, and deals with them (specify / register / reference them) differently.

> I hope that we'll investigate creating 3D TCRS in Testbed 18 or a future testbed. It could be important, for example, to specify a building floor plan at the the correct elevation and so on. I don't know too much about 3D processing, actually, so interested to see what the experts have to say.

Please take a look at the new [informative annex about additional dimensions](https://docs.opengeospatial.org/DRAFTS/17-083r3.html#annex-extending-additional-dimensions) in the 2DTMS revision, if you haven't already!

**Comment by prushforth** [comment] 2021-11-09 20:08
> perhaps it is somewhat like a different kind of CRSes like geodetic vs. geographic vs. projected. But TileMatrixSets have matrix, row, column identifiers, and then you still need additional coordinates within each tile's space. 

In TCRS "row" and "column" are axis names, and the coordinate system within each tile's space also have axis names (x,y), as do the pixels in the tcrs[zoom] array of coordinate systems (also "x" and "y").  The idea is that these coordinate systems (starting with the pcrs) are formally referenced to the body (earth) through a base CRS (gcrs).

I believe that a TCRS definition could be considered a "derived projected CRS" under [the NOTE paragraph of Section 9.2.2 of the OGC Abstract Specification Topic 2: Referencing by coordinates](https://docs.opengeospatial.org/as/18-005r4/18-005r4.html#33):

"A projected CRS is a coordinate reference system which is derived from a base geographic CRS....A projected CRS may act as the base CRS for a derived projected CRS" 



> So my feeling is that this is more of a policy/standards program issue than a technical capability to investigate. 

Investigating the technical capability will potentially prove or disprove the ability of existing encodings and software to deal with CRS defined this way.  Maybe after that it could be referred to the AB, if necessary.

> Please take a look at the new informative annex about additional dimensions in the 2DTMS revision, if you haven't already!

Thank you, interesting discussion. What I have been wondering about is the ability to treat zoom as a proxy measurement for a third vertical dimension, since it has a defined mathematical relation to elevation at a certain (set of) location(s).

>  In a single MapML payload, which simply provides features and their geometries, there is also not really a concept of Tiles at all.

The payload itself (can) represent a tile (or any other partitioning), so in theory, the feature coordinates could be expressed in pixels or any of the associated base CRS, so the TCRS name is necessary to understand how to place and render the pixels.  Also, we do have the reified \<tile> element, so I guess in theory also we could have a MapML payload that has a bunch of \<tile> elements containing \<feature> elements that are split by tile and so on.

**Comment by jerstlouis** [comment] 2021-11-09 20:42
> ... I believe that a TCRS definition could be considered a "derived projected CRS"

All that is sound, and as I mentioned that seems to be the way that the [DGGS specification](http://docs.opengeospatial.org/as/15-104r5/15-104r5.html#37) is organized.

> An OGC DGGS provides this globally in a structured form which is analogous to the ellipsoidal coordinate system described in ISO 19111 - spatial referencing by coordinates, but cell-based rather than continuous.

DGGS cells (or zones as they are now called) are similar in many ways to TileMatrixSets tiles, especially for axis-aligned DGGS where there is a lot of [commonality](https://github.com/opengeospatial/dggs-4-axis-aligned/issues/6).

However, as I mentioned the TileMatrixSet specification currently does not define them as a derived CRS. The particularity that you have two sets of coordinates, one for the tile, and then for within the tile, also puts them in a whole new category of CRS where they are not geodesic, geographic or projected. It seems that it would require a lot of efforts across OGC working groups (CRS SWG, Tiles SWG, DGGS SWG, OAB...) if that is the direction that this should take.

I don't see any reason why software should not be able to handle this if that is the direction taken by the standards, but I feel like efforts would be better spent achieving consensus on whether TileMatrixSets should be treated as a CRS before trying to get implementers to invest significant efforts to modify their software.

> Thank you, interesting discussion. What I have been wondering about is the ability to treat zoom as a proxy measurement for a third vertical dimension, since it has a defined mathematical relation to elevation at a certain (set of) location(s).

In our 3D geospatial visualization software, we want to use data with the right density for how it will get projected on the 2D screen. Looking down at the earth from high above will mean using a lower zoom level than if at low altitude, but so will looking at some feature far away in the distance looking towards the horizon. Similarly, looking down at features on the ground at the same distance from the ellipsoid but above Mount Everest vs. the Mariana Trench, data of different zoom level will be required. So in a 3D view you typically want a mix of different zoom levels for different visible areas, determined by the camera location as well as the digital elevation model.

> The payload itself (can) represent a tile (or any other partitioning), so in theory, the feature coordinates could be expressed in pixels or any of the associated base CRS, so the TCRS name is necessary to understand how to place and render the pixels.

Yes if the feature coordinates are expressed relative to the tile, that makes more sense to use the TCRS. Those would not really be "pixels" but either decimal coordinates relative to the tile's extent in normalized coordinates (e.g. 0..1 or -1..1 or -0.5..0.5), or quantized to an integer grid of finer resolution than the target device pixels (as in Mapbox Vector Tiles).

> Also, we do have the reified <tile> element, so I guess in theory also we could have a MapML payload that has a bunch of <tile> elements containing <feature> elements that are split by tile and so on.

One of the main advantages of tiles is that you can request deterministic pieces separately, and cache these efficiently (e.g. discarding least recently used tiles). It kind of defeats that purpose to stuff multiple tiles in a single document.
